/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_27_Desconto_Veiculos;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        float valorVeiculo = 1.0f, valorDesconto=0.0f, valorPago=0.0f, totalDescontos = 0.0f, totalPago = 0.0f;
        char tipoCombustivel;
        

        
        while(valorVeiculo != 0){
           System.out.println("Informe o valor do veículo");
           valorVeiculo = leitor.nextFloat();

           System.out.println("Informe o tipo de combustivel. Álcool - A | Gasolina - G | Disel - D");
           tipoCombustivel = leitor.next().charAt(0);

           if (tipoCombustivel == 'A' || tipoCombustivel == 'a'){
               valorDesconto = (valorVeiculo * 25) / 100;
           }else{
               if (tipoCombustivel == 'G' || tipoCombustivel == 'g'){
                   valorDesconto = (valorVeiculo * 21) / 100;
               }else{
                   if (tipoCombustivel == 'D' || tipoCombustivel == 'd'){
                       valorDesconto = (valorVeiculo * 14) / 100;
                   }
               }
           }
           valorPago = valorVeiculo - valorDesconto;
           totalDescontos = totalDescontos + valorDesconto;
           totalPago = totalPago + valorPago;
           
           System.out.println("Valor Desconto: "+valorDesconto);
           System.out.println("Valor Final: "+valorPago);
        }
        System.out.println("Total Descontos: "+totalDescontos);
        System.out.println("Total Pago: "+totalPago);
    }
}
