/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_09_Rendimento_Poupanca;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        float valorInicial, valorFinal;
        
        System.out.println("Digite o valor depositado na poupança (R$)");
        valorInicial = leitor.nextFloat();
        
        valorFinal = valorInicial + ((valorInicial * 7*1)/100);
        //J = C × i × t
        System.out.println("R$ " +valorInicial +" depositado 1 mês na poupança rende R$ " + valorFinal );
        
    }
}
