/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_30_Ordem_Crescente;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        int a,b, c;
        
         System.out.println("Digite a");
         a = leitor.nextInt();
        
         System.out.println("Digite b");
         b = leitor.nextInt();
         
         System.out.println("Digite c");
         c = leitor.nextInt();
        
        if (a > b){
            
           if (b > c) System.out.println(c +","+ b+", "+ a);       
           else                                             
               if (a > c)  System.out.println(b+","+ c+","+ a);   
               else  System.out.println( b+","+ a+","+ c);   
        }      
       else {                                                
           if (b > c)                                       
               if (a > c)  System.out.println( c+","+ a+","+ b);   
               else  System.out.println( a+","+ c+","+ b);         
           else  System.out.println( a +","+b+","+ c);  }           
          
    }
}
