/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_06_Trocar_Valores;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        int a, b, aux;
        
        System.out.println("Informe  o 1º valor");
        a = leitor.nextInt();
        
        System.out.println("Informe  o 2º valor");
        b = leitor.nextInt();
        
        System.out.println("Valores Finais");
        System.out.println("A = " + a + " B = " + b);
        
        aux = a; a = b; b = aux;
        
        System.out.println("Valores Finais");
        System.out.println("A = " + a + " B = " + b);
    }
}
