/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_14_Fatura;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);

        double preco;
        int quantidade;
        String numero, descricao;
        
        System.out.println("Informe numero fatura");
        numero = leitor.next();
        
        System.out.println("Informe descricao itens");        
        descricao = leitor.next();      
        
        System.out.println("Informe a quantidade");
        quantidade = leitor.nextInt();
        
        System.out.println("Informe o preço unitário");
        preco = leitor.nextDouble();        
        
        Fatura objFatura = new Fatura(numero, descricao, quantidade, preco);        
        
        System.out.println("Preco Total "+ objFatura.getTotalFatura());        
    }
}
