/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_15_Intervalo_100_200;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        int n1;
        
        System.out.println("Informe um numero");
        n1 = leitor.nextInt();
        
        if( n1  >= 100 && n1 <= 200){
            System.out.println(n1 +" Está no intervalo entre 100 e 200");
        }else{
            System.out.println(n1 +" Não está no intervalo entre 100 e 200");
        }
    }
}
