/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_06_Loja_Informatica;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Invoice objInvoice = new Invoice(123456, "Notebook Samsung", 5, 23000);   
                
        System.out.println("Preco Total: "+ objInvoice.getInvoiceAmount());
    }
}
