/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_22_Preco_Produto;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        float precoCusto, precoVenda, mediaCusto, mediaVenda;
        int totalCusto=0, totalVenda=0, i;

        
        for (i = 0; i < 4; i++){
            System.out.println("Informe o preço custo");          
            precoCusto = leitor.nextFloat();
            
            System.out.println("Informe o preço venda");          
            precoVenda = leitor.nextFloat();
            
            totalCusto = (int) (precoCusto + totalCusto) ;
            totalVenda = (int) (totalVenda + precoVenda);
                                   
           if( precoVenda > precoCusto){
                System.out.println("Lucro");
            }else{
                if( precoVenda < precoCusto){
                    System.out.println("Prejuizo");
                }
                else{
                    System.out.println("Empate");
                }
            }      
           //System.out.println("Preço de Custo: "+precoCusto);
           //System.out.println("Preço de Venda: "+precoVenda);
        }
        
        mediaCusto = totalCusto / i;
        mediaVenda = totalVenda / i;
        
        System.out.println("Média Custo: " +mediaCusto);
        System.out.println("Média Custo: " +mediaVenda);
    }
}
