/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_31_Operacao_Matematica;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        float a, b;
        char c;
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Informe A");
        a = leitor.nextFloat();
        
        System.out.println("Informe B");
        b= leitor.nextFloat();
        
        System.out.println("Informe C");
        c = leitor.next().charAt(0);
        
        if ( c == '+' || c == '-' || c == '*' || c == '/'){
            switch(c){
                case '+':
                    System.out.println("A + B = "+(a+b));
                    break;
                    
                case '-':
                    System.out.println("A - B = "+ (a-b));
                    break;
                    
                case '*':
                    System.out.println("A * B = "+ (a*b));
                    break;
                    
                case '/':
                    if (b==0){
                        System.out.println("A / B = "+a);
                    }else{
                        System.out.println("A / B = "+(a/b));   
                    }                    
                    break;
                    
                default:
                     System.out.println("operador não definido.");
            }
        
        }else{
                System.out.println("operador não definido.");
        }
        
    }
}
