/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_07_Converter_Temperatura;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        float celcius, fahrenheit;
        
        System.out.println("Digite a temperatura ºC");
        celcius = leitor.nextFloat();
        
        fahrenheit =(9*celcius+160) / 5;
        
        System.out.println(celcius +"º equivale "+fahrenheit+"ºf");
    }
}
