/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_03_Consumo_Medio_Automovel;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        float distancia, combustivel, medio;
        
        System.out.println("Informe a distância total percorrida pelo automóvel (km)");
        distancia = leitor.nextFloat();
        
        System.out.println("Informe total de combustível gasto (l)");
        combustivel = leitor.nextFloat();
        
        medio = distancia / combustivel;
        
        System.out.print("O Combústivel médio utilizado é " + medio + " litros");
        
    }
}
