/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exemplo_POO_Folha_Pagamento;

import java.util.Date;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Vendedor v = new Vendedor();
        v.setNome("Marcia");
        v.setSalario(1000.0f);
        v.setCpf("123.123.123-34");
        v.setDataNasc(new Date());
        v.setComissaoPorItem(10.0f);
        v.setTotaItensVendidos(50);
        
        System.out.print("Salario do Vendedor: "+v.calcularSalario());
                
        Motorista m = new Motorista();
    }
}
