/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_08_Converter_Dolar;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        float cotacao, dolar, real;
        
        System.out.println("Informe a cotação do Dolar hoje");
        cotacao = leitor.nextFloat();
        
        System.out.println("Informe quantidade de Dolares");
        dolar = leitor.nextFloat();
        
        real = dolar / cotacao;
        
        System.out.println(dolar + " Dolares equivalem a " + real + " Reais");
    }
}
