/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_05_Media_Aluno;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        float n1, n2, n3, media;
        String nome;
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Informe o nome do(a) aluno(a)");
        nome = leitor.nextLine();
                
        System.out.println("Informe 1ª nota");
        n1 = leitor.nextFloat();
        
        System.out.println("Informe 2ª nota");
        n2 = leitor.nextFloat();
        
        System.out.println("Informe 3ª nota");
        n3 = leitor.nextFloat();
        
        media = (n1 + n2 + n3) / 3;
        
        System.out.println("A média do(a) " +nome+ " é " + media);
    }
}
