/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_15_Funcionario;
import java.util.Scanner;
        
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        String nome,sobrenome; 
        double salarioMensal;
        
    //    for (int i = 0; i<2; i++){
           System.out.println("Informe o nome");
           nome = leitor.next();

           System.out.println("Informe o Sobrenome");
           sobrenome = leitor.next();

           System.out.println("Informe o Salario Mensal");
           salarioMensal = leitor.nextDouble();         
      //  }
        
           Funcionario objFuncionario = new Funcionario(nome, sobrenome, salarioMensal);
          // Funcionario objFuncionario2 = new Funcionario(nome, sobrenome, salarioMensal);
         
        System.out.println("Salario Mensal "+ objFuncionario.getSalarioMensal());        
        System.out.println("Salario Anual "+ objFuncionario.calcularSalarioAnual());
        System.out.println("Aumento "+ objFuncionario.calcularAumento());
        System.out.println("Novo Salario Mensal "+ objFuncionario.getSalarioMensal()); 
        System.out.println("Novo Salario Anual "+ objFuncionario.calcularSalarioAnual());
    }
}
