/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_04_Elevador;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Elevador objElevador = new Elevador();
        Scanner leitor = new Scanner(System.in);
        
        
        objElevador.inicializa(4, 6);
       
        //ENTRA
        if ( objElevador.entra(4) == false){
            System.out.println("Elevador Lotado");
        }else{
            System.out.println(objElevador.getQtdPessoas()+" Pessoas no Elevador ");
        }
        
        //SAI
        if ( objElevador.sai(1) == false){
            System.out.println("Elevador Vazio");
        } else{
            System.out.println(objElevador.getQtdPessoas()+" Pessoas no Elevador ");
        }    
        
        //SOBE
        if ( objElevador.sobe(6) == false){
            System.out.println("Voce esta no ultimo andar");
        } else{
            System.out.println(objElevador.getAndarAtual()+"º Andar");
        }        
        
        //DESCE
        if ( objElevador.desce(0) == false){
            System.out.println("Voce esta no terreo");
        } else{
            System.out.println(objElevador.getAndarAtual()+"º Andar");
        }         
    }
}
