/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_11_Ingresso;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Ingresso objIngresso = new Ingresso(800.0f);
        IngressoVip objIngressoVip = new IngressoVip(objIngresso.imprimirValor(), 50.0f);
        
        System.out.println("Preço Ingresso: " + objIngresso.imprimirValor());
        System.out.println("Preço Ingresso Vip: " + objIngressoVip.imprimirValorVip());
    }
}
