/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_07_Funcionario;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Funcionario objFuncionarioGerente = new Funcionario("Mayte", "Araujo", 18000);
        Funcionario objFuncionario = new Funcionario("Marilia", "Santana", 10000);                
        
        System.out.println("Funcionario: "+objFuncionarioGerente.getNome() +" Salario Anual: "+ objFuncionarioGerente.salarioAnual());
        System.out.println("Funcionario: "+objFuncionario.getNome() +" Salario Anual: "+ objFuncionario.salarioAnual());
        
        System.out.println("10% de Aumento");
        objFuncionarioGerente.calcularAumento();
        objFuncionario.calcularAumento();
        
        System.out.println("Funcionario: "+objFuncionarioGerente.getNome() +" Salario Anual: "+ objFuncionarioGerente.salarioAnual());
        System.out.println("Funcionario: "+objFuncionario.getNome() +" Salario Anual: "+ objFuncionario.salarioAnual());        
        
    }
}
