/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_25_Comparar_Numeros;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        int n1, n2;
        
        System.out.println("Digite 1º número");
        n1 = leitor.nextInt();
        
        System.out.println("Digite 2º número");
        n2 = leitor.nextInt();
        
        if ( n1 == n2){
            System.out.println("Números Iguais");
        }else{
            System.out.println("Números Diferentes");
            
            if ( n1  > n2){
                System.out.println(n1 +" é o maior");
            }else{
                if ( n2  > n1){
                    System.out.println(n2 +" é o maior");
                }
            }
        }
    }
}
