/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_20_Concessionaria;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);        
        char continuar ='s';
        float desconto, preco, pago;
        int ano, carro2000=0, total=0;
        
        while (continuar == 'S' || continuar == 's'){                        
            
            System.out.println("Informe o ano do veículo: ");
            ano = leitor.nextInt();
            
            System.out.println("Informe o preço atual do veículo: ");
            preco = leitor.nextFloat();            
            
            if( ano <= 2000){
                desconto = ( preco * 12) / 100;                
                carro2000++;
            }else{
                desconto = ( preco * 7) / 100;
            }            
            pago = preco-desconto;
            total++;
            System.out.println("Preço: "+pago);
            System.out.println("Desconto: "+desconto);
            
            System.out.println("Deseja calcular o desconto? S - Sim | N - Não");
            continuar = leitor.next().charAt(0);                      
        }
        System.out.println("Total de veículos: "+total);
        System.out.println("Total de veículos seminovos: "+carro2000);
    }
}
