/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_01_Soma;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        int n1, n2, soma;
        
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite o 1º número");
        n1 = leitor.nextInt();
        
        System.out.println("Digite o 1º número");
        n2 = leitor.nextInt();
        
        soma = n1 + n2;
        
        System.out.println("A soma de " + n1 + " + " + n2 + " = " + soma);
    }
}
