/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_13_Calculadora;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);        
        int n1=0, n2=0, OP=9;
        Calculadora objCalculadora = new Calculadora(n1, n2);
        CalculadoraCientifica objCalculadoraC = new CalculadoraCientifica(n1);       
        
        while(OP != 0){
            System.out.println("Selecione uma opção");
            System.out.println(""
                + "1 - Adição | \n"
                + "2 - Subtração | \n"
                + "3 - Muktiplicação | \n"
                + "4 - Divisão | \n"
                + "5 - Raiz Quadrada | \n"
                + "6 - Potenciação | \n"
                + "0 - Finalizar");
            OP = leitor.nextInt();      
            
            System.out.println("");
            switch(OP){
                case 1:
                    System.out.println("Informe 1º numero: ");
                    n1 = leitor.nextInt();

                    System.out.println("Informe 2º numero: ");
                    n2 = leitor.nextInt(); 
                    
                    System.out.println("Soma: "  + n1 + " + " + n2 + " = " +  objCalculadora.soma(n1, n2));
                    System.out.println("");
                    break;

                case 2:
                    System.out.println("Informe 1º numero: ");
                    n1 = leitor.nextInt();

                    System.out.println("Informe 2º numero: ");
                    n2 = leitor.nextInt();                     
                    
                    System.out.println("subtracao: " + n1 + " - " + n2 + " = " +  objCalculadora.subtracao(n1, n2));
                    System.out.println("");
                    break;                

                case 3:
                    System.out.println("Informe 1º numero: ");
                    n1 = leitor.nextInt();

                    System.out.println("Informe 2º numero: ");
                    n2 = leitor.nextInt();                     
                    
                    System.out.println("multiplicacao: " + n1 + " X " + n2 + " = " +  objCalculadora.multiplicacao(n1, n2));
                    System.out.println("");
                    break;

                case 4:                    
                    System.out.println("Informe 1º numero: ");
                    n1 = leitor.nextInt();

                    System.out.println("Informe 2º numero: ");
                    n2 = leitor.nextInt(); 
                    
                    System.out.println("divisao: " + n1 + " / " + n2 + " = " + objCalculadora.divisao(n1, n2));
                    System.out.println("");
                    break; 
                    
                case 5:                    
                    System.out.println("Informe 1º numero: ");
                    n1 = leitor.nextInt(); 
                    
                    System.out.println("A Raiz quadrada de: " + n1 + " = " + objCalculadoraC.raizQuadrada(n1));
                    System.out.println("");
                    break;

                case 6:                    
                    System.out.println("Informe 1º numero: ");
                    n1 = leitor.nextInt();
                    
                    System.out.println("Informe 2º numero: ");
                    n2 = leitor.nextInt(); 
                    
                    System.out.println( n1 + " elevado " + n2 + " = " + objCalculadoraC.potencia(n1, n2));
                    System.out.println("");
                    break;                    

                default:
                    System.out.println("Finalizando...");
            }               
        }
        
        
        
        

        
                             
    }
}
