/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_11_Valor_Venda;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        float precoCusto, vlVenda, acrescimo;
        
        System.out.println("Informe o preço de custo");
        precoCusto = leitor.nextFloat();
        
        System.out.println("Informe o % de acrescimo");
        acrescimo = leitor.nextFloat();
        
        vlVenda = precoCusto + (precoCusto * acrescimo)/100;
        
        System.out.println("Preço para venda: " +vlVenda);
    }
}
