/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_18_Maior_Idade;

import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        int[] idades = new int[75];
        
        for(int i = 0; i < 77; i++){
            System.out.println("Informe a "+ (i+1) + " idade");
            idades[i] = leitor.nextInt();
            
            if ( idades[i]  >= 18 ){
                 System.out.println("Maior de Idade");
            }else{
                System.out.println("Menor de Idade");
            }
            
        }
    }
}
