/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_04_Salario_Vendedor;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        String nome;
        float salarioFixo, valorTotalVendas, salarioFinal;

        System.out.println("Digite o nome do vendedor");
        nome = leitor.nextLine();
        
        System.out.println("Digite o Valor do Salario Fixo");
        salarioFixo = leitor.nextFloat();
        
        System.out.println("Digite o Valor Total de Vendas");
        valorTotalVendas = leitor.nextFloat();
        
        salarioFinal = salarioFixo + ((valorTotalVendas * 15)/ 100);
        
        System.out.println(nome);
        System.out.println("Salário Fixo: "+ salarioFixo);
        System.out.println("Salário este mês: "+salarioFinal);
        
    }
}
