/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_03_BombaCombustivel;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        String tpCombustivel="";
        
        BombaCombustivel objBombaCombustivel = new BombaCombustivel("Gasolina", 5.25f, 30.0f);
        
        System.out.println("Informe valor (R$) a Abastecer: " );
        System.out.println(objBombaCombustivel.abastecerPorValor(leitor.nextFloat())+" litros");
        
        System.out.println("Informe quantidade de Litros a abastecer: ");
        System.out.println("R$ "+ objBombaCombustivel.abastecerPorLitro(leitor.nextFloat()));
        
        System.out.println("Informe % de reajuste");        
        System.out.println("Novo preço do litro R$ " +objBombaCombustivel.alterarValor(leitor.nextFloat()));
        
        System.out.println("Informe um tipo de Combustivel Álcool | Gasolina | Disel ");        
        tpCombustivel = leitor.nextLine();        
        System.out.println( "Escolhio: " +objBombaCombustivel.alterarCombustivel(tpCombustivel));
        
        System.out.println("Informe Quantidade Combustivel Restante ");
        System.out.println(objBombaCombustivel.alterarQuantidadeCombustivel(leitor.nextFloat()));
    }
}
