/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exemplo_POO_IMC;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Pessoa objetoPessoa = new Pessoa(72.0f, 1.65f);
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Informe o peso");
        objetoPessoa.setPeso(leitor.nextFloat());
        
        System.out.println("Informe a altura");
        objetoPessoa.setAltura(leitor.nextFloat());
        
        System.out.println("IMC: "+ objetoPessoa.calcularIMC());
    }
}
