/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_10_Valor_Prestacoes;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        float vlCompra, vlPrestacoes;
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite o Valor da Compra");
        vlCompra = leitor.nextFloat();
        
        vlPrestacoes = vlCompra / 5;
        System.out.println("O valor das 5 prestações será R$ "+vlPrestacoes);
    }
}
