/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_17_Intervalo_10_150;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        int[] numeros = new int[80];
        int cont = 0;
        
        for(int i = 0; i < 80; i++){
            System.out.println("Digite o "+(i+1)+" número");
            numeros[i] = leitor.nextInt();
            
            if( numeros[i] >=10 && numeros[i] <= 150 ){
                cont++;
            }
        }
        
        System.out.println(cont +" números estão entre 10 e 150");
    }
}
