/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_23_Compara_numeros;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        int n1;
        
        System.out.println("Informe um número");
        n1 = leitor.nextInt();
        
        if (n1 > 80){
            System.out.println("Número maior que 80");
        }else{
            if (n1 < 25){
                System.out.println("Número menor que 25");
            }else{
                if (n1 == 40){
                    System.out.println("Número igual 40");
                }
            }
        }
    }
}
