/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_POO_12_Agenda;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);                        
        
        System.out.println("Entre com o nome da agenda");
        String nome = leitor.next(); 
        
        Agenda agenda = new Agenda(nome);        
        int idade=0;
        float altura=0.0f;
         
        Contato[] contatos = new Contato[3];                          
        
        for (int i=0; i<3; i++){
            System.out.println("Entre com as informações do contato " + (i+1));
            Contato contato = new Contato(nome, idade, altura);        
            
            System.out.println("Informe o nome");
            nome = leitor.next();
            contato.setNome(nome);
            
            System.out.println("Informe o idade");
            idade = leitor.nextInt();
            contato.setIdade(idade);

            System.out.println("Informe o altura");
            altura = leitor.nextFloat();            
            contato.setAltura(altura);
            
            contatos[i] = contato;
        }
        
        agenda.setContato(contatos);
        
        if (agenda != null){
            System.out.println(agenda.obterInfo());
            
            System.out.println("Informe o nome");
            System.out.println(agenda.buscarPessoa(nome));
            
        }        
    }
}
