/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio_19_Homens_mulheres;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Scanner leitor = new Scanner(System.in);
        String[] nome = new String[5];
        int[] idade = new int [5];
        char[] sexo = new char[5];
        int mulheres=0, homens=0;        
        
        for (int i = 0; i < 5; i++){
            
            System.out.println("Informe o nome");
            nome[i] = leitor.nextLine();
            
            System.out.println("Informe a idade");
            idade[i] = leitor.nextInt();
            
            System.out.println("Informe o sexo M ou F");
            sexo[i] = leitor.next().charAt(0);
            
            if (sexo[i] == 'M' || sexo[i] == 'm'){
                System.out.println(nome[i] +" é Homem");
                homens++;
            }else{
                if (sexo[i] == 'F' || sexo[i] == 'f'){
                    System.out.println(nome[i] +" é Mulher");
                    mulheres++;
                }
            }  
            System.out.println("***********");
        }
        
        System.out.println("Total de Homens " + homens);
        System.out.println("Total de Mulheres " + mulheres);
        
    }
}
